export const SET_TRAININGS = 'SET_TRAININGS';
export const SET_TRAININGS_LOADING = 'SET_TRAININGS_LOADING';
export const SET_TRAININGS_MESSAGE = 'SET_TRAININGS_MESSAGE';

export const SET_SESSIONS = 'SET_SESSIONS';
export const SET_SESSIONS_LOADING = 'SET_SESSIONS_LOADING';
export const SET_SESSIONS_MESSAGE = 'SET_SESSIONS_MESSAGE';

export const SET_SUBSESSIONS = 'SET_SUBSESSIONS';
export const SET_SUBSESSIONS_LOADING = 'SET_SUBSESSIONS_LOADING';
export const SET_SUBSESSIONS_MESSAGE = 'SET_SUBSESSIONS_MESSAGE';

export const SET_PRACTICES = 'SET_PRACTICES';
export const SET_PRACTICES_LOADING = 'SET_PRACTICES_LOADING';
export const SET_PRACTICES_MESSAGE = 'SET_PRACTICES_MESSAGE';

export const SET_PHOTOS = 'SET_PHOTOS';

export const SET_USER = 'SET_USER';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const SET_LOGIN_MESSAGE = 'SET_LOGIN_MESSAGE';

export const SET_HELP = 'SET_HELP';
export const SET_ABOUT = 'SET_ABOUT';

export const READ_ITEMS = 'READ_ITEMS';
export const READ_PHOTOS = 'READ_PHOTOS';
export const READ_ABOUT = 'READ_ABOUT';
export const READ_HELP = 'READ_HELP';

export const LOGIN = 'LOGIN';
export const NAVIGATE = 'NAVIGATE';

export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const FILTER_PRACTICES = 'FILTER_PRACTICES';
export const SET_FILTER_PRACTICES = 'SET_FILTER_PRACTICES';
export const SET_FILTER_PRACTICES_LOADING = 'SET_FILTER_PRACTICES_LOADING';
export const SET_FILTER_PRACTICES_MESSAGE = 'SET_FILTER_PRACTICES_MESSAGE';

export const SET_ALL_SUBSESSIONS_LOADING = 'SET_ALL_SUBSESSIONS_LOADING';
export const SET_ALL_SUBSESSIONS_MESSAGE = 'SET_ALL_SUBSESSIONS_MESSAGE';
export const READ_ALL_SUBSESSIONS = 'READ_ALL_SUBSESSIONS';
export const SET_ALL_SUBSESSIONS = 'SET_ALL_SUBSESSIONS';

export const SET_TEAM_NEWS_LOADING = 'SET_TEAM_NEWS_LOADING';
export const SET_TEAM_NEWS_MESSAGE = 'SET_TEAM_NEWS_MESSAGE';
export const SET_TEAM_NEWS = 'SET_TEAM_NEWS';
export const READ_TEAM_NEWS = 'READ_TEAM_NEWS';

export const SET_CHAT_CONFIG_LOADING = 'SET_CHAT_CONFIG_LOADING';
export const SET_CHAT_CONFIG_MESSAGE = 'SET_CHAT_CONFIG_MESSAGE';
export const SET_CHAT_CONFIG = 'SET_CHAT_CONFIG';
export const READ_CHAT_CONFIG = 'READ_CHAT_CONFIG';

export const SET_CHAT_ROOMS_LOADING = 'SET_CHAT_ROOMS_LOADING';
export const SET_CHAT_ROOMS_MESSAGE = 'SET_CHAT_ROOMS_MESSAGE';
export const SET_CHAT_ROOMS = 'SET_CHAT_ROOMS';
export const READ_CHAT_ROOMS = 'READ_CHAT_ROOMS';
